config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root                              'home#index'

  get   'about'                 =>  'home#about'
  get   'faq'                   =>  'home#faq'
  get   'contact'               =>  'contacts#new'
  get   'old_contact'           =>  'home#contact'

  resources :prerequisites
  resources :courses
  resources :contacts

end

app/models/program.rb
class Program < ActiveRecord::Base

  has_many :courses

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]

  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.search(params[:search]).all.paginate(:per_page => 5, :page => params[:page])
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:name, :description)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_for(@program) do |f| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% @program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form' %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/index.html.erb
<%= form_tag programs_path, :method => 'get' do %>
  <p>
    <br>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>



<p id="notice"><%= notice %></p>

<% @page_header="List of Programs" %>

    <% @programs.each do |program| %>

      <hr>
        <p><a data-toggle="collapse" href="#program<%= program.id %>" class='program-name'><%= program.name %></a></p>

        <div id='<%= "program#{program.id}" %>' class="collapse">
          <p class='program-description-tag'>Description: </p>
          <p class='program-description'> <%= program.description %></p>
      </div>
  <% end %>
<br>
<%= will_paginate @programs %>


<br>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form' %>

<%= link_to 'Back', programs_path %>

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @program.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>