config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root                              'home#index'

  get   'about'                 =>  'home#about'
  get   'faq'                   =>  'home#faq'
  get   'contact'               =>  'contacts#new'
  get   'old_contact'           =>  'home#contact'

  resources :prerequisites
  resources :courses
  resources :contacts

end

app/models/prerequisite.rb
require 'tree'

class Prerequisite < ActiveRecord::Base
  belongs_to :course

  def print_tree(t)
    if t.has_children?
      if t.content.operator == Operator.where(name: "and").first.id
        op = " and "
      else
        op = " or "
      end
      return "(" + self.print_tree(t['left'].content) + op + self.print_tree(t['right'].content) + ")"
    else
      p = t.content
      c = Course.find(p.operandA).name
      g = Grade.find(p.operandB).name
      return "(" + c + " >= " + g + ")"
    end
  end

  def descendant_tree
    if has_children?
      l, r = children
      node = Tree::TreeNode.new(id.to_s, self)
      node << Tree::TreeNode.new("left", l.descendant_tree)
      node << Tree::TreeNode.new("right", r.descendant_tree)
      return node
    else
      node = Tree::TreeNode.new(id.to_s, self)
      return node
    end
  end

  def children
    return [Prerequisite.find(operandA), Prerequisite.find(operandB)]
  end

  def has_children?
    # TODO: don't have to find 'and' and 'or' operator every time this method is called.
    # What a poor ORM ActiveRecord... does not it support 'or' method?
    ids = Operator.where("name = 'and' or name = 'or'").all.map { |op| op.id }
    return ids.include?(operator)
  end
end

app/controllers/prerequisites_controller.rb
class PrerequisitesController < ApplicationController
  before_action :set_prerequisite, only: [:show, :edit, :update, :destroy]

  # GET /prerequisites
  # GET /prerequisites.json
  def index
    @prerequisites = Prerequisite.all
  end

  # GET /prerequisites/1
  # GET /prerequisites/1.json
  def show
  end

  # GET /prerequisites/new
  def new
    @prerequisite = Prerequisite.new
  end

  # GET /prerequisites/1/edit
  def edit
  end

  # POST /prerequisites
  # POST /prerequisites.json
  def create
    @prerequisite = Prerequisite.new(prerequisite_params)

    respond_to do |format|
      if @prerequisite.save
        format.html { redirect_to @prerequisite, notice: 'Prerequisite was successfully created.' }
        format.json { render :show, status: :created, location: @prerequisite }
      else
        format.html { render :new }
        format.json { render json: @prerequisite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prerequisites/1
  # PATCH/PUT /prerequisites/1.json
  def update
    respond_to do |format|
      if @prerequisite.update(prerequisite_params)
        format.html { redirect_to @prerequisite, notice: 'Prerequisite was successfully updated.' }
        format.json { render :show, status: :ok, location: @prerequisite }
      else
        format.html { render :edit }
        format.json { render json: @prerequisite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prerequisites/1
  # DELETE /prerequisites/1.json
  def destroy
    @prerequisite.destroy
    respond_to do |format|
      format.html { redirect_to prerequisites_url, notice: 'Prerequisite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prerequisite
      @prerequisite = Prerequisite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prerequisite_params
      params.require(:prerequisite).permit(:operator, :operandA, :operandB)
    end
end

app/helpers/prerequisites_helper.rb
module PrerequisitesHelper
end

app/views/prerequisites/_form.html.erb
<%= form_for(@prerequisite) do |f| %>
  <% if @prerequisite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prerequisite.errors.count, "error") %> prohibited this prerequisite from being saved:</h2>

      <ul>
      <% @prerequisite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :operator %><br>
    <%= f.number_field :operator %>
  </div>
  <div class="field">
    <%= f.label :operandA %><br>
    <%= f.number_field :operandA %>
  </div>
  <div class="field">
    <%= f.label :operandB %><br>
    <%= f.number_field :operandB %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prerequisites/edit.html.erb
<h1>Editing Prerequisite</h1>

<%= render 'form' %>

<%= link_to 'Show', @prerequisite %> |
<%= link_to 'Back', prerequisites_path %>

app/views/prerequisites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Prerequisites</h1>

<table>
  <thead>
    <tr>
      <th>Operator</th>
      <th>Operanda</th>
      <th>Operandb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prerequisites.each do |prerequisite| %>
      <tr>
        <td><%= prerequisite.operator %></td>
        <td><%= prerequisite.operandA %></td>
        <td><%= prerequisite.operandB %></td>
        <td><%= link_to 'Show', prerequisite %></td>
        <td><%= link_to 'Edit', edit_prerequisite_path(prerequisite) %></td>
        <td><%= link_to 'Destroy', prerequisite, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prerequisite', new_prerequisite_path %>

app/views/prerequisites/new.html.erb
<h1>New Prerequisite</h1>

<%= render 'form' %>

<%= link_to 'Back', prerequisites_path %>

app/views/prerequisites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Operator:</strong>
  <%= @prerequisite.operator %>
</p>

<p>
  <strong>Operanda:</strong>
  <%= @prerequisite.operandA %>
</p>

<p>
  <strong>Operandb:</strong>
  <%= @prerequisite.operandB %>
</p>

<%= link_to 'Edit', edit_prerequisite_path(@prerequisite) %> |
<%= link_to 'Back', prerequisites_path %>