config/routes.rb
Rails.application.routes.draw do

  resources :programs
  root                              'home#index'

  get   'about'                 =>  'home#about'
  get   'faq'                   =>  'home#faq'
  get   'contact'               =>  'contacts#new'
  get   'old_contact'           =>  'home#contact'

  resources :prerequisites
  resources :courses
  resources :contacts

end

app/views/layouts/_header.html.erb
<% if !@page_header.blank? %>
  <div class="main_header container">
    <h1><%= @page_header %></h1>
    <% if !notice.blank? or !alert.blank? %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "UNM Catalog
      ", root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Courses",      courses_path %></li>
        <li><%= link_to "Programs",      programs_path %></li>
        <li><%= link_to "FAQ",          faq_path %></li>
        <li><%= link_to "Contact Us",   contact_path %></li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? "UNM Catalog | #{@page_title}" : "UNM Catalog" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="site-wrapper">
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>